[build]
  command = "npm install"
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose", "passport", "cors"]
  directory = "api" 

[functions.timeout]
    max = 60 

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
